runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /.*
  script: main.app

env_variables:
    CLOUDSQL_CONNECTION_NAME: JFOWEJOIFE
    CLOUDSQL_USER: FJWEOJFEW
    CLOUDSQL_PASSWORD: FJWEIJFOEW

libraries:
- name: MySQLdb
  version: "latest"
  